# Task custom param
tasks: [PE]       # default: [PE, MP, MC, FPE, 2DAR]

# Global task param. Do not change.
task_to_flag: {'PE': 0, 'MP': 1, 'FPE': 2, 'MC': 3, '2DAR': 4, 'AR': 5}
flag_to_task: {'0': 'PE', '1': 'MP', '2': 'FPE', '3': 'MC', '4': '2DAR', '5': 'AR'}
task_metrics:
    PE: [PE e1, PE e2]
    MP: [MP]
    FPE: [FPE]
    MC: [MC]
    2DAR: [2DAR]
    AR: [AR]

func_ver:
  dataset_action_recognition: 1
  evaluate_action_recognition: 2
  train_epoch: 2
  
  dataset_non_AR: 0
  evaluate_non_AR: 0
  train_epoch_non_AR: 0




merge_double_action: 'no'  # 'before_pre_logits'; 'before_head'; 'after_output'; 'no'

train_feeder_args_ntu:
    data_path: /home/pami_ICL/CTR-GCN/data/ntu/NTU60_CS.npz
    split: train
    debug: False
    random_choose: False
    random_shift: False
    random_move: False
    window_size: 60         # 64 in CTR-GCN
    normalization: False
    random_rot: True       # True in CTR-GCN
    p_interval: [0.5, 1]       # [0.5, 1] in CTR-GCN
    vel: False
    bone: False
test_feeder_args_ntu:
  data_path: /home/pami_ICL/CTR-GCN/data/ntu/NTU60_CS.npz
  split: test
  window_size: 60           # 64 in CTR-GCN
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False
batch_size_ntu: 32
test_batch_size_ntu: 64

# Data
use_partial_data: True
# Uncomment and fill the lines below and set use_partial_data: True, if you want to create a subset of data as you wish, for quick debugging
partial_data:   
    datasets:
        PE: partial_data/H36M_PE/Actions6_ClipLen256_SampleStride1_TrainStride64
        MP: partial_data/AMASS/TrainShift400_TestShift100_ClipLen16_In10_Out10
        FPE: partial_data/H36M_FPE/Actions6_ClipLen32_SampleStride1_TrainStride64
        MC: partial_data/3DPW_MC/TrainShift2_TestShift4_DropRatios46_ClipLen16
        2DAR: partial_data/NTU60_2DAR/Actions30_LabelStride2_2DAR
    train_stride: 64           # 64
    sample_stride: 1
    clip_len: 256                # 16
    num_joints: 17  ######################################################################################
    drop_ratios_MC: [0.4, 0.6]
    root_path: data
    source_file_h36m: source_data/H36M_Actions6.pkl
    clip_len_2DAR: 60  ######################################################################################
    batch_size_2DAR: 16
    label_stride_2DAR: 2
full_data:
    datasets:
        PE: H36M
        MP: AMASS
        FPE: H36M_FPE
        MC: 3DPW_MC
        2DAR: NTU60_2DAR
    train_stride: 16
    sample_stride: 1
    clip_len: 16
    num_joints: 17
    drop_ratios_MC: [0.4, 0.6]
    root_path: data
    source_file_h36m: source_data/H36M.pkl
    clip_len_2DAR: 31
    batch_size_2DAR: 9999999
    label_stride_2DAR: 1


# Model
backbone: SiC_dynamicTUP         # SiC_dynamicTUP (default); SiC_staticTUP
maxlen: 16  ######################################################################################
dim_in: 3
dim_out: 3
dim_feat: 256
mlp_ratio: 2
depth: 5
dim_rep: 256
num_heads: 8
att_fuse: True

# Traning
epochs: 120
batch_size: 4                # default: 200
test_batch_size: 512
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99

# Loss
losses:
  mpjpe: 1.
  n_mpjpe: 0.
  velocity: 0.
  limb_var: 0.
  limb_gt: 0.
  angle: 0.
  angle_velocity: 0.

# Data processing
label_type_2DAR: default               # default; cube_xyz
rootrel_input: True
rootrel_input_2DAR: False
rootrel_target_MP: True
rootrel_target_PE: True
rootrel_target_FPE: True
flip_h36m_y_axis: False
flip_h36mFPE_y_axis: False
scale_h36m_skeleton: 2.0
scale_h36mFPE_skeleton: 2.0

# General
no_eval: False

# Unify skeletons from different datasets
amass_to_h36m: [[2], [0], [3], [6], [1], [4], [7], [5], [8], [8,11], [11], [10], [13], [15], [9], [12], [14]]
